### ISSUE TITLE
Is the JSX example wrong?

### ISSUE THREAD

**Issue by LeBenLeBen** [amcharts/amcharts3-react#17]
The JSX example says:

```
<AmCharts.React {...} />
```

But it doesn’t work for me. I was able to make it work by using:

```
<AmCharts {...} />
```

Did I miss something or there’s just a typo in the example?

**Comment by Pauan** [comment]
Hi @LeBenLeBen,

If you are using Webpack, then you must use `AmCharts` rather than `AmCharts.React`

This is already mentioned [in the README](https://github.com/amcharts/amcharts3-react/blob/f4216ee87b51879e8ca0d8456b3649c9bb7fa23c/README.md#if-you-are-using-a-bundler-like-webpack-or-browserify), but I will change it to be more clear.

**Comment by Pauan** [comment]
Fixed: https://github.com/amcharts/amcharts3-react/commit/44182ff1f1c2df0339a1a5d08470a835a1e3adec
