### ISSUE TITLE
React is not defined. 

### ISSUE THREAD

**Issue by julianljk** [amcharts/amcharts3-react#3]
I'm importing React via npm so when AmCharts.React tries to do React.createClass, it can't find React since its not in the scope of window. Does that mean that unless I import React and ReactDOM via a script tag in window, I can't use this?

**Comment by msimonc** [comment]
Good question, I have the same question, thanks

**Comment by Pauan** [comment]
I just now added in support for Webpack.

You can see more details [here](https://github.com/amcharts/amcharts3-react#if-you-are-using-a-bundler-like-webpack-or-browserify).

You can also see [here](https://github.com/amcharts/amcharts3-react/tree/master/examples/webpack) for an example app that uses Webpack and amcharts3-react.

Since this has now been solved, I'm going to close this issue. Please open a new issue if you are still having problems.
