### ISSUE TITLE
Settings a Language for AmCharts for React+Webpack

### ISSUE THREAD

**Issue by Kivylius** [amcharts/amcharts3-react#32]
Hi,

Is there anyway to set a language for amCharts for react? i tried `.."language": "zh",` but it seems not to work, according to the official documentation that all i need. I look inside the `node_modules` folder and can see `node_modules/amcharts3/amcharts/lang/zh.js` so I included:

    require("amcharts3/amcharts/lang/zh");

And it works, but sure is this correct way to do it?

Thanks

**Comment by Pauan** [comment]
Hi @Kivylius

I'm sorry for the delay. We've released `amcharts3-react` version 2.0, which uses a [different system for loading AmCharts](https://github.com/amcharts/amcharts3-react/blob/master/documentation/Migrating%20to%202.0.md#migrating-to-amcharts-react-plugin-20).

Rather than using `require`, you must instead use `<script>` tags in your HTML, like this:

```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

You can find more details [here](https://github.com/amcharts/amcharts3-react/blob/master/documentation/Migrating%20to%202.0.md#migrating-to-amcharts-react-plugin-20).

After changing to the new system, it is no longer necessary to use `require("amcharts3/amcharts/lang/zh");`

Instead, `"language": "zh"` should be enough.
