### ISSUE TITLE
Export amchart

### ISSUE THREAD

**Issue by Kinetic-Pulse** [amcharts/amcharts3-react#36]
Hey There,

I am using Meteor + React (jsx style)

I have the charts rendering and this all working fine.
I have now added the require('amcharts3-export'); module on the top of my file.

I get the following error in the browser console when the charts render:
'Uncaught SyntaxError: Unexpected token <' for the files:
fabric.min.js:1
FilSaver.min.js:1
jszip.js:1
xlsx.min.js:1

This is the line mentioned in all of the files:
"< ! DOCTYPE html >"

I assume it might be something to do with the way Meteor loads the files? But am not sure.
Any advice would be much appreciated.

Thanks

**Comment by Pauan** [comment]
Hi @Kinetic-Pulse

We've released `amcharts3-react` version 2.0, which uses a [different system for loading AmCharts](https://github.com/amcharts/amcharts3-react/blob/master/documentation/Migrating%20to%202.0.md#migrating-to-amcharts-react-plugin-20).

Rather than using `require`, you must instead use `<script>` tags in your HTML, like this:

```
<link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />

<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
<script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
```

You can find more details [here](https://github.com/amcharts/amcharts3-react/blob/master/documentation/Migrating%20to%202.0.md#migrating-to-amcharts-react-plugin-20).
