### ISSUE TITLE
Pie Chart

### ISSUE THREAD

**Issue by ivgrin** [amcharts/amcharts3-react#38]
Please, update index.js:

require("amcharts3/amcharts/amcharts.js");
require("amcharts3/amcharts/serial.js");
require("amcharts3/amcharts/themes/light.js");

// add this line to make pie charts work
require("amcharts3/amcharts/pie.js");

**Comment by Pauan** [comment]
Hi @ivgrin 

We've released `amcharts3-react` version 2.0, which uses a different system for loading AmCharts.

Rather than using `require`, you must instead use `<script>` tags in your HTML, like this:

```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
<script src="https://www.amcharts.com/lib/3/pie.js"></script>
```

You can find more details [here](https://github.com/amcharts/amcharts3-react/blob/master/documentation/Migrating%20to%202.0.md#migrating-to-amcharts-react-plugin-20).
