### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by aapostol87** [amcharts/amcharts3-react#39]
We are trying to use the export functionality but we stumbled upon a problem. 
As you can see in the console (screen shot attached) there is a problem with including the export functionality dependencies.

![screenshot from 2017-03-28 12-00-53](https://cloud.githubusercontent.com/assets/22098076/24451930/8ef11318-1489-11e7-94a8-2d1c5d3d2ad8.png)

Attached you can find the [source code](https://github.com/amcharts/amcharts3-react/files/878801/export.zip) for the case.

Can you please provide a technical solution to this problem?

Thank you, 
Andrei

**Comment by Pauan** [comment]
Hi Andrei,

I'm sorry for the delay, I had to make some significant changes to `amcharts3-react` in order to fix this issue.

1. We now have an npm package for `amcharts3-react`. In your `package.json` you should change `"amcharts3-react": "amcharts/amcharts3-react"` to `"@amcharts/amcharts3-react": "^2.0.0"`

2. In addition, you should completely remove `amcharts/amcharts3`, `amcharts/export`, `fabric`, and `react-amcharts` from your `package.json`

3. In your HTML file, you must now load AmCharts using `<script>` tags:

   ```html
   <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />

   <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
   <script src="https://www.amcharts.com/lib/3/serial.js"></script>
   <script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
   <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
   ```

   This is the same as in [the demos](https://www.amcharts.com/demos/)

4. You must change `import AmCharts from 'amcharts3-react';` to `import AmCharts from '@amcharts/amcharts3-react';`

5. You must remove the other AmCharts imports, such as `require("amcharts3-export");`

After making all of those changes, it should work correctly.

If you continue to have any problems, let me know and I'll help you further.

**Comment by thilinaucsc** [comment]
I use these import file
import '/node_modules/amcharts3/amcharts/amcharts'
import '/node_modules/amcharts3/amcharts/serial'
import '/node_modules/amcharts3/amcharts/pie'
import '/node_modules/amcharts3/amcharts/themes/light'
import '/node_modules/amcharts3/amcharts/plugins/export/export.min'
import '/node_modules/amcharts3/amcharts/gauge'
import '/node_modules/amcharts3/amcharts/plugins/export/libs/pdfmake/pdfmake.min.js'
import '/node_modules/amcharts3/amcharts/plugins/export/libs/FileSaver.js/FileSaver.min'
import '/node_modules/amcharts3/amcharts/plugins/export/libs/fabric.js/fabric.min'
// import '/node_modules/amcharts3/amcharts/plugins/export/libs/jszip/jszip.min'
// import '/node_modules/amcharts3/amcharts/plugins/export/libs/xlsx/xlsx.min'
import '/node_modules/amcharts3/amcharts/plugins/export/export.css'
import '/node_modules/amcharts3/amcharts/plugins/responsive/responsive'
import BaseComponent from '../components/BaseComponent.jsx';
import AmCharts from '@amcharts/amcharts3-react';

but not work for me
